"""
    format_angle(parts; delim=':'; digits=2, pad=true)

Given the `(whole, minutes, seconds)` parts of an angle, will format into a
string with the given delimiter(s). These parts can be generated by the
`xxx2dms` and `xxx2hms` methods, for sexagesimal and `hour:minute:second`
outputs. Multiple delimiters can be given in a tuple or vector placed after
their respective values. For more control over formatting, consider using
[Printf](https://docs.julialang.org/en/v1/stdlib/Printf/) or a package like
[Format.jl](https://github.com/JuliaString/Format.jl).

If any input is `Missing`, returns `missing`.

# Examples
```jldoctest
julia> ang = 45.0; # degrees

julia> format_angle(deg2dms(ang))
"45:0:0.0"

julia> format_angle(deg2hms(ang); pad=true)
"03:00:00.00"

julia> format_angle(rad2hms(1.5), delim=["h", "m", "s"]; pad=true)
"05h43m46.48s"

julia> format_angle(rad2hms(1.5), delim=["h", "m", "s"]; digits=5)
"5h43m46.48062"

julia> format_angle(rad2hms(1.5), delim=["h", "m", "s"]; digits="all")
"5h43m46.48062470963538s"
```

# See also
[`deg2dms`](@ref), [`deg2hms`](@ref), [`rad2dms`](@ref), [`rad2hms`](@ref), [`ha2dms`](@ref), [`ha2hms`](@ref)
"""

format_angle(angle; delim=':', kwargs...) = format_angle(angle, delim; kwargs...)
format_angle(angle, delim::Union{<:AbstractString, Char}; kwargs...) = format_angle(angle, [delim]; kwargs...)
format_angle(w, m, s; kwargs...) = format_angle((w, m, s); kwargs...)
format_angle(::Missing; kwargs...) = missing
format_angle(::Missing, args...; kwargs...) = missing

function format_angle(angle, delim::Union{<:AbstractVector, <:Tuple}; digits::Union{Int, String}=2, pad::Bool=false)
    whole, min, sec, delim = angle..., collect(delim)
    sgn = signbit(whole) ? '-' : ""

    whole, min = trunc.(Int, [whole, min])
    sec = digits == "all" ? sec : round(sec; digits)
    if pad
      whole, min = lpad.([whole, min], 2, "0")
      sec = join(lpad.(split("$sec", "."), 2, "0"), ".")
    end
  
    angle = string.(Any[whole, min, sec])
    printout = length(delim) == 1 ? join(angle, delim[begin]) : permutedims([angle delim])[:]
    return string(length(delim) == 1 ? sgn : "", printout...)
end
